-- 코드를 작성해주세요

SELECT ID, n.FISH_NAME, t1.LENGTH FROM 
(SELECT FISH_TYPE, MAX(LENGTH) as LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) t1
INNER JOIN FISH_INFO i ON i.FISH_TYPE = t1.FISH_TYPE AND i.LENGTH = t1.LENGTH
INNER JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE
ORDER BY ID ASC;